#!/bin/bash

remote_branch="dev"
SCRIPTPATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PROJECT_ROOT=${SCRIPTPATH}/../..

while read local_ref local_sha remote_ref remote_sha
do
    # Check if pushing to the dev branch
    if [[ "$remote_ref" == "refs/heads/$remote_branch" ]]; then
        echo "Pushing to $remote_branch branch detected. Running script..."
        
        ${PROJECT_ROOT}/tools/bump_version.sh
        
        if [ $? -ne 0 ]; then
            echo "Script execution failed. Aborting push."
            exit 1
        fi
    fi
done

exit 0
