.TH MKDOTENV 1 "January 2026" "mkdotenv 1.0.0"
.SH NAME
mkdotenv \- A command-line tool that populates secrets upon a .env file from a template.
.SH DESCRIPTION
The \fmkdotenv\fR command allows users to poopulate environmental variables from a template file by placing appropriate markup upon the file..SH SYNOPSIS
.B mkdotenv
[\fI--help\fR|\fI-h\fR][\fI--version\fR|\fI-v\fR]
[\fI--environment\fR|\fI-e\fR |\fI--env\fR]
[\fI--template-file\fR|\fI-t\fR |\fI--template\fR][\fI--output-file\fR|\fI-o\fR]
[\fI--argument\fR|\fI-a\fR |\fI--arg\fR]
.SH AUTHOR
Written by Desyllas Dimitrios.

.SH BUGS
Report issues at https://github.com/pc-magas/mkdotenv/issues

.SH SEE ALSO
.BR dotenv (1)
