package params

var flagsMeta = FlagList{
    {
        Name:     "help",
        Aliases:  []string{},
		Short: "h",
        Required: false,
        Usage:    "Display help message and exit",
        AllowMultiple: false,
		Type:  	BoolType,
        Order:    0,
    },
    {
        Name:     "version",
        Aliases:  []string{},
		Short: "v",
        Required: false,
        AllowMultiple: false,
		Type:  	BoolType,
        Usage:    "Display version and exit",
        Order:    0,
    },
    {
        Name:     "environment",
        Aliases:  []string{"env"},
        AllowMultiple: false,
		Short: "e",
		Type: StringType,
        Required: false,
		DefaultValue: ".env,dist",
        Usage:    "Environment in which secrets would be resolved",
        Order:    1,
		Validator: ValiDateCommon,
    },
    {
        Name:     "template-file",
        Aliases:  []string{"template"},
		Short: "t",
        AllowMultiple: false,
		Type: StringType,
        Required: false,
		DefaultValue: ".env.dist",
        Usage:    "Template .env file containing commands on how .env file would be generated",
        Order:    2,
		Validator: ValiDateCommon,
    },
    {
        Name:     "output-file",
        Aliases:  []string{},
        Short: "o",
		Type: StringType,
        AllowMultiple: false,
        Required: false,
		DefaultValue: ".env",
        Usage:    "File to write output to",
        Order:    2,
		Validator: ValiDateCommon,
    },
    {
        Name:     "argument",
        Aliases:  []string{"arg"},
		Short: "a",
        AllowMultiple: true,
		Type: StringType,
        Required: false,
		DefaultValue: "",
        Usage:    "Template .env file containing commands on how .env file would be generated",
        Order:    3,
		Validator: ValiDateCommon,
    },
}