// Code generated by MockGen. DO NOT EDIT.
// Source: ./core/executor/command_executor.go
//
// Generated by this command:
//
//	mockgen -source=./core/executor/command_executor.go -destination=./core/executor/mock_command_executor.go -package=executor
//

// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	context "github.com/pc-magas/mkdotenv/core/context"
	parser "github.com/pc-magas/mkdotenv/core/parser"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(command *parser.MkDotenvCommand, ctx context.ResolutionContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", command, ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(command, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), command, ctx)
}
