name: test_build_macos

on:
  push:
    branches:
      - dev
        
jobs:

  mac_intel_build:
    runs-on: macos-13
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true
      
      - name: Compile and install
        run: |
          make
          sudo make install
      
      - name: test_run
        run: mkdotenv --help

  test_compile:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true
      
      - name: Compile and install
        run: |
          make
          sudo make install
      
      - name: test_run
        run: mkdotenv --help
