name: build_macos

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  mac_build:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true

      - name: run
        run: |
          bash macos/build.sh
      
      - name: test_homebrew
        run: |
          brew install --formula ./macos/bin/mkdotenv.rb

      - name: test_install
        run: |
          mkdotend --help

     