name: build_macos

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  mac_build:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run tests
        run: |
          make test
      
      - name: run
        run: |
          make test_run


     