name: build_macos

on:
  workflow_dispatch:
  
jobs:
  mac_build:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true

      - name: Run tests
        run: |
          make test
      
      - name: run
        run: |
          make test_run

      - name: run
        run: |
          bash macos/build.sh

     