name: build_and_release

on:
  push:
    branches:
      - master

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true
      
      - run: go build -v -o mkdotenv ./src/mkdotenv.go

      - name: get version
        id: version
        run: |
          echo "version=$(grep 'const VERSION' ./src/mkdotenv.go | sed -E 's/.*"([^"]+)".*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mkdotenv"
