name: build_and_release_docker

on:
  push:
    branches:
      - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: |
          make docker-push