name: build_and_release_docker

on:
  push:
    branches:
      - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get version
        id: version
        run: |
          echo "version=$(grep 'const VERSION' ./src/mkdotenv.go | sed -E 's/.*"([^"]+)".*/\1/')" >> "$GITHUB_OUTPUT"


      - name: Build Docker
        env: 
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t pcmagas/mkdotenv:${VERSION} -t pcmagas/mkdotenv:latest .
          docker push pcmagas/mkdotenv:${VERSION} 
          docker push pcmagas/mkdotenv:latest