name: release

on:
  push:
    branches:
      - dev
      - master

jobs:
  tag_git:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_version: ${{ steps.set_tag_version.outputs.tag_version }}
      is_pre: ${{steps.is_pre.outputs.tag_version}}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get version
        id: version
        run: |
          echo "version=$(grep 'const VERSION' ./src/mkdotenv.go | sed -E 's/.*"([^"]+)".*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Set tag version
        id: set_tag_version
        run: |

          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "tag_version=${{ steps.version.outputs.version }}-pre" >> "$GITHUB_OUTPUT"
            echo "is_pre=true" >> "$GITHUB_OUTPUT"
          else
            echo "tag_version=${{ steps.version.outputs.version }}" >> "$GITHUB_OUTPUT"
            echo "is_pre=false" >> "$GITHUB_OUTPUT"
          fi
      

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.set_tag_version.outputs.tag_version }}
        
      - name: Push tags
        run: git push --tags
  
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build_image
        if: github.ref == 'refs/heads/dev'
        run: make docker

      - name: release_image
        if: github.ref == 'refs/heads/master'
        run:
          make docker-push


  build_bin:
    runs-on: ubuntu-latest
    needs: tag_git
    
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true

      - name: build
        run: make bin

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdotenv-bin
          path: mkdotenv  
  
  build_deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: tag_git
    steps:

      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SECRET }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | awk '/sec/{print $2}' | cut -d'/' -f2)
          echo "DEB_SIGN_KEYID=$KEY_ID" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install golang-1.23-go debhelper make build-essential debhelper equivs

      - name: Show Key ID
        run: echo "Using DEB_SIGN_KEYID=$DEB_SIGN_KEYID"

      - name: build
        run: make deb
   
      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdotenv-deb
          path: mkdotenv*.deb  

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: 
      - tag_git
      - build_bin
      - build_deb
    steps:

      - uses: actions/checkout@v4
        with:
         fetch-depth: 0


      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdotenv-bin

      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdotenv-deb

      - name: Create a GitHub pre release
        if:   github.ref == 'refs/heads/dev'
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{needs.tag_git.outputs.tag_version}}"
          allowUpdates: true
          prerelease:  true
          artifacts: mkdotenv*.deb, mkdotenv

      - name: Create a GitHub release
        if:  github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{needs.tag_git.outputs.tag_version}}"
          allowUpdates: true
          prerelease:  false
          artifacts: mkdotenv*.deb, mkdotenv
      