name: test_release

on:
  push:
    branches:
      - dev

jobs:
  build_binary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: true
      
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install equivs
          sudo apt install build-essential debhelper

      - name: Build App
        run: |
          make ci

      - name: get version
        id: version
        run: |
          echo "version=$(grep 'const VERSION' ./src/mkdotenv.go | sed -E 's/.*"([^"]+)".*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Set tag version
        id: set_tag_version
        run: |

          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "tag_version=${{ steps.version.outputs.version }}-pre" >> "$GITHUB_OUTPUT"
          else
            echo "tag_version=${{ steps.version.outputs.version }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: mkdotenv, mkdotenv*.deb
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}