name: test_prerelease

on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:

      - name: Do something on prelease
        run: echo "Hello"