name: release-ppa

on:
  push:
    branches:
      - master

jobs:
  upload_ppa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SECRET }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | awk '/sec/{print $2}' | cut -d'/' -f2)
          echo "DEB_SIGN_KEYID=$KEY_ID" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install golang-1.23-go golang-go debhelper make build-essential dput

      - name: Show Key ID
        run: echo "Using DEB_SIGN_KEYID=$DEB_SIGN_KEYID"

      - run: make ppa